application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "habit_tracker"
  require_ssl: false
redis_uri: "redis://127.0.0.1:6379"