application:
  host: 127.0.0.1
  base_url: "http://localhost"
  signing_key: "b7210sTYnYeMgjsWWSVm9aIquVZhIL2vPKxurnVXCqoJJlaxcEi3shy61YV9fW6X"
  cookie_secure: false
  cors_origin: "http://localhost:8100"
database:
  require_ssl: false